### ISSUE TITLE
Not all key-value pairs of the name parts are inline

### ISSUE THREAD

**Issue by jpretired** [ric2016/compact_themes_adjuster#1]
Hi Richard,
as I said at webtrees.net forum I very appreciate your module and I am sure I will use it for my family webtrees.
Now I would like to say that not all key-value pairs of the name are inline as shown on the screenshot:
![image](https://user-images.githubusercontent.com/350656/60987070-26c29980-a341-11e9-92c6-8e43b72b12cb.png)
Regards, Josef

**Comment by ric2016** [comment]
This is a bug in webtrees and has already been fixed in the current version (via https://github.com/fisharebest/webtrees/pull/2465), it just hasn't been released yet.

**Comment by jpretired** [comment]
Thank you, with the fix you mentioned the issue is cleared.
Josef
