### ISSUE TITLE
v 2.0.1.2

### ISSUE THREAD

**Issue by jpretired** [ric2016/compact_themes_adjuster#7]
I downloaded and implemented version 2.0.1.2 and got this error:

`ReflectionException: Class Cissee\WebtreesExt\IndividualNameHandler does not exist in /var/www/Projekty/webtrees-2/vendor/illuminate/container/Container.php:788 Stack trace: #0 /var/www/Projekty/webtrees-2/vendor/illuminate/container/Container.php(788): ReflectionClass->__construct('Cissee\\Webtrees...') #1 /var/www/Projekty/webtrees-2/vendor/illuminate/container/Container.php(667): Illuminate\Container\Container->build('Cissee\\Webtrees...') #2 /var/www/Projekty/webtrees-2/vendor/illuminate/container/Container.php(615): Illuminate\Container\Container->resolve('Cissee\\Webtrees...', Array) #3 /var/www/Projekty/webtrees-2/app/Helpers/functions.php(45): Illuminate\Container\Container->make('Cissee\\Webtrees...') #4 /var/www/Projekty/webtrees-2/modules_v4/compact_themes_adjuster-master/CompactThemesAdjusterModule.php(93): app('Cissee\\Webtrees...') #5 /var/www/Projekty/webtrees-2/app/Services/ModuleService.php(817): CompactThemes\CompactThemesAdjusterModule->boot() #6 /var/www/Projekty/webtrees-2/app/Http/Middleware/BootModules.php(60): Fisharebest\Webtrees\Services\ModuleService->bootModules(Object(Fisharebest\Webtrees\Module\ColorsTheme)) #7 /var/www/Projekty/webtrees-2/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #8 /var/www/Projekty/webtrees-2/app/Http/Middleware/LoadRoutes.php(76): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #9 /var/www/Projekty/webtrees-2/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #10 /var/www/Projekty/webtrees-2/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #11 /var/www/Projekty/webtrees-2/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}(Object(Illuminate\Database\MySqlConnection)) #12 /var/www/Projekty/webtrees-2/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction(Object(Closure), 3) #13 /var/www/Projekty/webtrees-2/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #14 /var/www/Projekty/webtrees-2/app/Http/Middleware/DoHousekeeping.php(81): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #15 /var/www/Projekty/webtrees-2/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #16 /var/www/Projekty/webtrees-2/app/Http/Middleware/UseTheme.php(70): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #17 /var/www/Projekty/webtrees-2/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #18 /var/www/Projekty/webtrees-2/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #19 /var/www/Projekty/webtrees-2/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #20 /var/www/Projekty/webtrees-2/app/Http/Middleware/UseLanguage.php(73): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #21 /var/www/Projekty/webtrees-2/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #22 /var/www/Projekty/webtrees-2/app/Http/Middleware/UseSession.php(73): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #23 /var/www/Projekty/webtrees-2/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #24 /var/www/Projekty/webtrees-2/app/Http/Middleware/UseFilesystem.php(58): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #25 /var/www/Projekty/webtrees-2/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseFilesystem->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #26 /var/www/Projekty/webtrees-2/app/Http/Middleware/UseCache.php(74): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #27 /var/www/Projekty/webtrees-2/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseCache->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #28 /var/www/Projekty/webtrees-2/app/Http/Middleware/UpdateDatabaseSchema.php(58): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #29 /var/www/Projekty/webtrees-2/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #30 /var/www/Projekty/webtrees-2/app/Http/Middleware/UseDebugbar.php(67): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #31 /var/www/Projekty/webtrees-2/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #32 /var/www/Projekty/webtrees-2/app/Http/Middleware/UseDatabase.php(90): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #33 /var/www/Projekty/webtrees-2/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #34 /var/www/Projekty/webtrees-2/vendor/middlewares/client-ip/src/ClientIp.php(81): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #35 /var/www/Projekty/webtrees-2/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #36 /var/www/Projekty/webtrees-2/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #37 /var/www/Projekty/webtrees-2/app/Http/Middleware/HandleExceptions.php(75): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #38 /var/www/Projekty/webtrees-2/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #39 /var/www/Projekty/webtrees-2/app/Http/Middleware/BaseUrl.php(77): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #40 /var/www/Projekty/webtrees-2/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #41 /var/www/Projekty/webtrees-2/app/Http/Middleware/ReadConfigIni.php(65): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #42 /var/www/Projekty/webtrees-2/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #43 /var/www/Projekty/webtrees-2/app/Http/Middleware/SecurityHeaders.php(47): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #44 /var/www/Projekty/webtrees-2/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #45 /var/www/Projekty/webtrees-2/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #46 /var/www/Projekty/webtrees-2/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #47 /var/www/Projekty/webtrees-2/app/Http/Middleware/PhpEnvironment.php(49): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #48 /var/www/Projekty/webtrees-2/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\PhpEnvironment->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #49 /var/www/Projekty/webtrees-2/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #50 /var/www/Projekty/webtrees-2/index.php(55): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest)) #51 {main}`

**Comment by ric2016** [comment]
Do you have all files from the zip file? In particular `IndividualNameHandler.php` within the folder `patchedWebtrees`?

**Comment by jpretired** [comment]
Yes, unzipped and copied everything.

**Comment by jpretired** [comment]
Sorry Richard, my fault - the privacy setting of the folder was wrong.
Now it works OK. Please delete this issue completely. Thanks

**Comment by ric2016** [comment]
No problem!
