### ISSUE TITLE
Upgrade version URL

### ISSUE THREAD

**Issue by fisharebest** [ric2016/compact_themes_adjuster#8]
The function `customModuleLatestVersionUrl()` should be the URL of a file that contains the latest version number.

A file in the github repository is perfect for this. For example
`https://raw.githubusercontent.com/ric2016/compact_themes_adjuster/master/LATEST-VERSION.txt`

From webtrees 2.0.3, any available upgrades will be shown in the control panel.

TIP: the latest version is cached for 24 hours.  While developing, you may need to delete `data/cache/*` to force a reload.

----------

<img width="582" alt="Screen Shot 2020-02-09 at 11 54 16" src="https://user-images.githubusercontent.com/2306088/74101588-47e7a480-4b33-11ea-8058-53db19a4c4a8.png">

**Comment by ric2016** [comment]
Fixed for this and all other 2.x modules.
